config/routes.rb
Rails.application.routes.draw do
  resources :currencies
  devise_for :users
  get 'home/about'
  get 'home/lookup'
  post "/home/lookup" => 'home/lookup'
  root 'home#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency.rb
class Currency < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :currencies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all
    require 'net/http'
    require 'json'

    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response  = Net::HTTP.get(@uri)
    @lookup_crypto = JSON.parse(@response)
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create

    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render :show, status: :created, location: @currency }
      else
        format.html { render :new }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { render :show, status: :ok, location: @currency }
      else
        format.html { render :edit }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url, notice: 'Currency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end

    def correct_user
      @correct = current_user.currencies.find_by(id: params[:id])
      redirect_to currencies_path, notice: "Not Authorized To Edit This Entry" if @correct.nil?
    end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'

    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response  = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
    @my_coins = ["BTC", "XRP", "ADA", "XLM", "STEEM",]
  end

  def about
  end

  def lookup

    require 'net/http'
    require 'json'

    @url = 'https://api.coinmarketcap.com/v1/ticker/'
    @uri = URI(@url)
    @response  = Net::HTTP.get(@uri)
    @lookup_coins = JSON.parse(@response)




    @symbol = params[:sym]

    if @symbol
    @symbol = @symbol.upcase
    end

    if @symbol == ""
      @symbol = "You didn't enter anything."
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/currencies/_form.html.erb
<%= form_with(model: currency, local: true) do |form| %>
  <% if currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% currency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol%>
  </div>

  <div class="field">
    <%= form.number_field :user_id, value: current_user.id, type: "hidden" %>
  </div>

  <div class="field">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per %>
  </div>

  <div class="field">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<% profit_loss = 0  %>
<h1>Currencies</h1>
<br>
<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Current Price</th>
      <th>Rank</th>
      <th>1 Hr %</th>
      <th>24 Hr %</th>
      <th>7 Day %</th>
      <th>Current Value</th>
      <th>Total Paid</th>
      <th>Profit/Loss</th>
      <th>Cost Paid Per</th>
      <th>Amount owned</th>
    </tr>
  </thead>

  <tbody>
    <% @currencies.each do |currency| %>
      <tr>
        <% if currency.user_id == current_user.id %>
          <% if currency.symbol %>
            <% currency.symbol = currency.symbol.upcase %>
            <% end %>
            <% for x in @lookup_crypto %>
              <% if currency.symbol == x["symbol"] %>
                <td><%= link_to x["name"], currency %></td>
                <td>$<%= x["price_usd"] %></td>
                <td><%= x["rank"] %></td>
                <td><%= x["percent_change_1h"] %>%</td>
                <td><%= x["percent_change_24h"] %>%</td>
                <td><%= x["percent_change_7d"] %>%</td>
                <td>$<%= x["price_usd"].to_d * currency.amount_owned %></td>
                <td>$<%= currency.cost_per * currency.amount_owned %></td>
                <td><%=(x["price_usd"].to_d * currency.amount_owned) - (currency.cost_per * currency.amount_owned) %></td>

                <% profit_loss += (x["price_usd"].to_d * currency.amount_owned) - (currency.cost_per * currency.amount_owned) %>

              <% end %>
            <% end %>
            <td>$<%= currency.cost_per %></td>
            <td><%= currency.amount_owned %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <strong>Portfolio Profit/Loss: </strong> <%= number_to_currency(profit_loss) %>

  <br><br><br>

  <%= link_to 'New Currency', new_currency_path, class: "btn btn-default" %>

app/views/currencies/new.html.erb
<h1>New Currency</h1>

<%= render 'form', currency: @currency %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <p>
      <strong>Symbol:</strong>
      <%= @currency.symbol %>
    </p>

    <p>
      <strong>Cost per:</strong>
      <%= @currency.cost_per %>
    </p>

    <p>
      <strong>Amount owned:</strong>
      <%= @currency.amount_owned %>
    </p>

    <div class="panel-footer">

      <%= link_to 'Back', currencies_path %>
      |
      <%= link_to 'Edit', edit_currency_path(@currency) %>
      |
      <%= link_to 'Delete', currency_path(@currency), method: :delete, data: { confirm: 'Are you sure?' } %>

    </div>

  </div>
</div>

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible">
    <button class ="close" data-dismiss="alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
          <%= link_to "Crypto Portfolio", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Me", home_about_path %></li>
        <li><%= link_to "Look Up", home_lookup_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "List Crypto", currencies_path %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Add New", new_currency_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Log In", user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>My name is Arthur Truong</p>

app/views/home/index.html.erb
<div class="jumbotron">
  <h2>The Finest Crypto Management Tool Ever.</h2>
  <p>Immerse yourself with control - Arthur</p>
  <p><a class="btn btn-default btn-lg" href="#" role="button">Learn more</a></p>
</div>

app/views/home/lookup.html.erb
<h3>Crypto Currency Lookup</h3>
<br>

<%= form_tag home_lookup_path, :method => 'POST' do %>
  <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol', size: 50 , class: "form-control"%>
  <br>
  <%= submit_tag 'Lookup Stock Quote', class: "btn btn-primary form-control" %>
<% end %>

<br><br>

<%= @symbol %>
<!-- if @symbol exist -->
<% if @symbol %>
<% for x in @lookup_coins %>
    <% if @symbol == x["symbol"] %> <br>
      <%= x["name"] %> : $<%= x["price_usd"] %><br>
        Rank <%= x["rank"] %>
    <% end %>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto Currency Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
    <%= render 'home/flash' %>
    <%= yield %>
    </div>
  </body>
</html>